package vn.freshlink.delivery;

import java.time.*;import java.util.*;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
import vn.freshlink.common.api.ApiResponse;import vn.freshlink.identity.Actor;

@RestController @RequestMapping("/api")
public class DeliveryWorkflowController {
 private final JdbcTemplate jdbc;public DeliveryWorkflowController(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public record TripUpdate(@NotNull Long driverId,@NotNull Long originId,@NotEmpty @Size(max=50) List<@NotNull Long> stopIds,@Size(max=1000) String note){}
 public record Reason(@NotBlank @Size(max=500) String reason,@Size(max=40) String reasonCode){}
 public record Location(@NotNull @DecimalMin("-90") @DecimalMax("90") Double latitude,@NotNull @DecimalMin("-180") @DecimalMax("180") Double longitude,Instant eta){}
 private Map<String,Object> trip(long id){var r=jdbc.queryForList("SELECT * FROM delivery_trips WHERE trip_id=? FOR UPDATE",id);if(r.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy chuyến");return r.get(0);}
 private void audit(Actor a,String action,String type,long id,String note){jdbc.update("INSERT INTO audit_logs(actor_user_id,action_code,entity_type,entity_id,new_data) VALUES (?,?,?,?,JSON_OBJECT('note',?))",a.userId(),action,type,id,note);}
 @PutMapping("/trips/{id}") @Transactional public ApiResponse<?> update(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody TripUpdate x){a.requireRole("OPERATIONS_COORDINATOR");var t=trip(id);if(!Set.of("PLANNED","LOADING").contains(t.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Chuyến đã bắt đầu và không thể sửa");if(new HashSet<>(x.stopIds()).size()!=x.stopIds().size())throw new IllegalArgumentException("Điểm giao bị lặp");if(jdbc.queryForObject("SELECT COUNT(*) FROM users u JOIN organization_members m ON m.user_id=u.user_id JOIN member_roles mr ON mr.member_id=m.member_id JOIN roles r ON r.role_id=mr.role_id WHERE u.user_id=? AND u.status='ACTIVE' AND m.status='ACTIVE' AND r.role_code='DRIVER'",Integer.class,x.driverId())==0)throw new IllegalArgumentException("Tài xế không hoạt động");if(jdbc.queryForObject("SELECT COUNT(*) FROM addresses WHERE address_id=? AND active=TRUE AND address_type='CROSS_DOCK'",Integer.class,x.originId())!=1)throw new IllegalArgumentException("Điểm xuất phát không hợp lệ");var current=jdbc.queryForList("SELECT trip_stop_id FROM trip_stops WHERE trip_id=? ORDER BY stop_sequence",Long.class,id);if(current.size()!=x.stopIds().size()||!new HashSet<>(current).equals(new HashSet<>(x.stopIds())))throw new IllegalArgumentException("Danh sách phải chứa đúng các điểm giao của chuyến");jdbc.update("UPDATE trip_stops SET stop_sequence=stop_sequence+1000 WHERE trip_id=?",id);for(int i=0;i<x.stopIds().size();i++)jdbc.update("UPDATE trip_stops SET stop_sequence=? WHERE trip_id=? AND trip_stop_id=?",i+1,id,x.stopIds().get(i));jdbc.update("UPDATE delivery_trips SET driver_user_id=?,origin_address_id=?,note=? WHERE trip_id=?",x.driverId(),x.originId(),x.note(),id);audit(a,"UPDATE_TRIP","TRIP",id,"driver/route updated");return ApiResponse.success(id,"Đã cập nhật chuyến");}
 @PostMapping("/trips/{id}/cancel") @Transactional public ApiResponse<?> cancel(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Reason x){a.requireRole("OPERATIONS_COORDINATOR");var t=trip(id);if(!Set.of("PLANNED","LOADING").contains(t.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Chuyến đã bắt đầu và không thể hủy");var allocations=jdbc.queryForList("SELECT DISTINCT ba.batch_allocation_id,ba.batch_id,ba.allocated_quantity FROM trip_stops s JOIN delivery_items di ON di.trip_stop_id=s.trip_stop_id JOIN batch_allocations ba ON ba.batch_allocation_id=di.batch_allocation_id WHERE s.trip_id=? AND ba.allocation_status IN ('PICKED','LOADED') FOR UPDATE",id);for(var x1:allocations)jdbc.update("UPDATE batch_allocations SET allocation_status='RESERVED' WHERE batch_allocation_id=?",x1.get("batch_allocation_id"));jdbc.update("UPDATE customer_orders o JOIN trip_stops s ON s.order_id=o.order_id SET o.order_status='SOURCING' WHERE s.trip_id=? AND o.order_status='READY_FOR_DELIVERY'",id);jdbc.update("UPDATE delivery_trips SET status='CANCELLED',cancelled_at=UTC_TIMESTAMP(3),cancellation_reason=? WHERE trip_id=?",x.reason(),id);jdbc.update("UPDATE trip_stops SET status='SKIPPED' WHERE trip_id=? AND status='PENDING'",id);audit(a,"CANCEL_TRIP","TRIP",id,x.reason());return ApiResponse.success(id,"Đã hủy chuyến");}
 @PostMapping("/stops/{id}/location") @Transactional public ApiResponse<?> location(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Location x){var rows=jdbc.queryForList("SELECT s.*,t.driver_user_id,t.status trip_status FROM trip_stops s JOIN delivery_trips t ON t.trip_id=s.trip_id WHERE s.trip_stop_id=? FOR UPDATE",id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy điểm giao");var s=rows.get(0);if(((Number)s.get("driver_user_id")).longValue()!=a.userId()&&!a.hasRole("OPERATIONS_COORDINATOR"))throw new org.springframework.security.access.AccessDeniedException("Không phải tài xế của chuyến");if(!"IN_PROGRESS".equals(s.get("trip_status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Chuyến chưa chạy");jdbc.update("UPDATE trip_stops SET last_latitude=?,last_longitude=?,location_updated_at=UTC_TIMESTAMP(3),eta_at=? WHERE trip_stop_id=?",x.latitude(),x.longitude(),x.eta()==null?null:java.sql.Timestamp.from(x.eta()),id);return ApiResponse.success(id,"Đã cập nhật vị trí");}
 @PostMapping("/stops/{id}/arrive") @Transactional public ApiResponse<?> arrive(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Location x){location(a,id,x);if(jdbc.update("UPDATE trip_stops SET status='ARRIVED',actual_arrival_at=UTC_TIMESTAMP(3) WHERE trip_stop_id=? AND status='PENDING'",id)!=1)throw new ResponseStatusException(HttpStatus.CONFLICT,"Điểm giao không chờ đến");jdbc.update("INSERT INTO delivery_events(trip_stop_id,event_type,actor_user_id,latitude,longitude,note) VALUES (?,'DRIVER_ARRIVED',?,?,?,'Driver arrived')",id,a.userId(),x.latitude(),x.longitude());return ApiResponse.success(id,"Đã báo đến điểm");}
 @PostMapping("/stops/{id}/fail") @Transactional public ApiResponse<?> fail(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Reason x){var rows=jdbc.queryForList("SELECT s.*,t.driver_user_id,t.status trip_status FROM trip_stops s JOIN delivery_trips t ON t.trip_id=s.trip_id WHERE s.trip_stop_id=? FOR UPDATE",id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy điểm giao");var s=rows.get(0);if(((Number)s.get("driver_user_id")).longValue()!=a.userId())throw new org.springframework.security.access.AccessDeniedException("Không phải tài xế của chuyến");if(!Set.of("PENDING","ARRIVED").contains(s.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Điểm giao đã kết thúc");String code=x.reasonCode()==null?"OTHER":x.reasonCode();if(jdbc.queryForObject("SELECT COUNT(*) FROM delivery_failure_reasons WHERE reason_code=? AND active=TRUE",Integer.class,code)!=1)throw new IllegalArgumentException("Mã lý do giao thất bại không hợp lệ");jdbc.update("UPDATE trip_stops SET status='FAILED',failure_reason=?,failure_reason_code=?,completed_at=UTC_TIMESTAMP(3) WHERE trip_stop_id=?",x.reason(),code,id);jdbc.update("INSERT INTO delivery_events(trip_stop_id,event_type,actor_user_id,note) VALUES (?,'DELIVERY_FAILED',?,?)",id,a.userId(),x.reason());audit(a,"FAIL_DELIVERY","TRIP_STOP",id,x.reason());return ApiResponse.success(id,"Đã ghi nhận giao thất bại");}
}
