package vn.freshlink.system;
import java.math.*;import java.time.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import vn.freshlink.common.*;import vn.freshlink.common.api.ApiResponse;import vn.freshlink.identity.Actor;
@RestController @RequestMapping("/api") public class PlatformFeaturesController{
 private final JdbcTemplate jdbc;private final Sql sql;public PlatformFeaturesController(JdbcTemplate j,Sql s){jdbc=j;sql=s;}
 @GetMapping("/notifications") public ApiResponse<?> notifications(@AuthenticationPrincipal Actor a,@RequestParam(defaultValue="false") boolean unreadOnly,@RequestParam(defaultValue="50") @Min(1) @Max(200) int limit){return ApiResponse.success(jdbc.queryForList("SELECT * FROM notifications WHERE user_id=? AND (?=FALSE OR read_at IS NULL) ORDER BY created_at DESC LIMIT ?",a.userId(),unreadOnly,limit),"Thông báo");}
 @GetMapping("/notifications/unread-count") public ApiResponse<?> unreadCount(@AuthenticationPrincipal Actor a){Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM notifications WHERE user_id=? AND read_at IS NULL",Integer.class,a.userId());return ApiResponse.success(java.util.Map.of("unread_count",count==null?0:count),"Số thông báo chưa đọc");}
 @PostMapping("/notifications/{id}/read") public ApiResponse<?> read(@AuthenticationPrincipal Actor a,@PathVariable long id){if(jdbc.update("UPDATE notifications SET read_at=COALESCE(read_at,UTC_TIMESTAMP(3)) WHERE notification_id=? AND user_id=?",id,a.userId())!=1)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy thông báo");return ApiResponse.success(id,"Đã đọc");}
 @PostMapping("/notifications/read-all") public ApiResponse<?> readAll(@AuthenticationPrincipal Actor a){return ApiResponse.success(jdbc.update("UPDATE notifications SET read_at=UTC_TIMESTAMP(3) WHERE user_id=? AND read_at IS NULL",a.userId()),"Đã đọc tất cả");}
 @GetMapping("/admin/audit-logs") public ApiResponse<?> audit(@AuthenticationPrincipal Actor a,@RequestParam(required=false) String entityType,@RequestParam(required=false) Long entityId,@RequestParam(defaultValue="100") @Min(1) @Max(500) int limit){a.requireRole("SYSTEM_ADMIN");String q="SELECT l.*,u.email actor_email FROM audit_logs l LEFT JOIN users u ON u.user_id=l.actor_user_id WHERE (? IS NULL OR l.entity_type=?) AND (? IS NULL OR l.entity_id=?) ORDER BY l.occurred_at DESC LIMIT ?";return ApiResponse.success(jdbc.queryForList(q,entityType,entityType,entityId,entityId,limit),"Audit log");}
 @GetMapping("/admin/login-history") public ApiResponse<?> logins(@AuthenticationPrincipal Actor a,@RequestParam(defaultValue="100") @Min(1) @Max(500) int limit){a.requireRole("SYSTEM_ADMIN");return ApiResponse.success(jdbc.queryForList("SELECT * FROM login_history ORDER BY occurred_at DESC LIMIT ?",limit),"Lịch sử đăng nhập");}
  @GetMapping("/analytics/kpis") public ApiResponse<?> kpis(@AuthenticationPrincipal Actor a,@RequestParam LocalDate from,@RequestParam LocalDate to){if(to.isBefore(from)||java.time.temporal.ChronoUnit.DAYS.between(from,to)>366)throw new IllegalArgumentException("Khoảng thời gian không hợp lệ");a.requireRole("SYSTEM_ADMIN","OPERATIONS_COORDINATOR","QUALITY_INSPECTOR","CUSTOMER_SUPPORT","ACCOUNTANT");var out=new java.util.LinkedHashMap<String,Object>();out.put("orders",jdbc.queryForMap("SELECT COUNT(*) total,SUM(order_status='DELIVERED') delivered,SUM(order_status='CANCELLED') cancelled,COALESCE(SUM(total_amount),0) value FROM customer_orders WHERE delivery_date BETWEEN ? AND ?",from,to));out.put("delivery",jdbc.queryForMap("SELECT COUNT(*) stops,SUM(status='DELIVERED') delivered,SUM(status='FAILED') failed,SUM(actual_arrival_at IS NOT NULL AND planned_arrival_at IS NOT NULL AND actual_arrival_at<=planned_arrival_at) on_time FROM trip_stops WHERE DATE(created_at) BETWEEN ? AND ?",from,to));out.put("quality",jdbc.queryForMap("SELECT COUNT(*) inspections,SUM(final_result IN ('PASS','PARTIAL_PASS')) passed,SUM(final_result IN ('FAIL')) failed,AVG(CASE WHEN accepted_quantity+review_quantity+rejected_quantity>0 THEN accepted_quantity/(accepted_quantity+review_quantity+rejected_quantity)*100 END) acceptance_rate FROM batch_inspections WHERE DATE(inspected_at) BETWEEN ? AND ?",from,to));out.put("claims",jdbc.queryForMap("SELECT COUNT(*) total,SUM(status IN ('RESOLVED','CLOSED')) completed,AVG(TIMESTAMPDIFF(HOUR,submitted_at,COALESCE(resolved_at,closed_at))) avg_resolution_hours FROM complaints WHERE DATE(submitted_at) BETWEEN ? AND ?",from,to));out.put("receivables",jdbc.queryForMap("SELECT COALESCE(SUM(i.total_amount - COALESCE((SELECT SUM(CASE WHEN p.payment_type='REFUND' THEN -p.amount ELSE p.amount END) FROM payments p WHERE p.order_id=i.order_id AND p.status='CONFIRMED'),0)),0) actual_balance, COALESCE(SUM(CASE WHEN i.status='OVERDUE' THEN (i.total_amount - COALESCE((SELECT SUM(CASE WHEN p.payment_type='REFUND' THEN -p.amount ELSE p.amount END) FROM payments p WHERE p.order_id=i.order_id AND p.status='CONFIRMED'),0)) ELSE 0 END),0) overdue_balance, COALESCE(SUM(i.total_amount),0) invoiced FROM invoices i WHERE DATE(i.issued_at) BETWEEN ? AND ?",from,to));return ApiResponse.success(out,"KPI");}
 public record Rating(@NotNull Long orderId,@NotNull Long supplierId,@NotNull @Min(1) @Max(5) Integer score,@Size(max=1000) String comment){}
 @PostMapping("/supplier-ratings") @Transactional public ApiResponse<?> rate(@AuthenticationPrincipal Actor a,@jakarta.validation.Valid @RequestBody Rating r){var o=jdbc.queryForMap("SELECT restaurant_id,order_status FROM customer_orders WHERE order_id=?",r.orderId());long org=((Number)o.get("restaurant_id")).longValue();a.requireOrganization(org,"RESTAURANT_MANAGER");if(!"DELIVERED".equals(o.get("order_status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Chỉ đánh giá sau khi giao xong");if(jdbc.queryForObject("SELECT COUNT(*) FROM batch_allocations ba JOIN batches b ON b.batch_id=ba.batch_id JOIN order_items i ON i.order_item_id=ba.order_item_id WHERE i.order_id=? AND b.supplier_id=?",Integer.class,r.orderId(),r.supplierId())==0)throw new IllegalArgumentException("Nhà cung cấp không tham gia đơn");jdbc.update("INSERT INTO supplier_ratings(restaurant_id,supplier_id,order_id,score,comment,created_by) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE score=VALUES(score),comment=VALUES(comment),created_by=VALUES(created_by)",org,r.supplierId(),r.orderId(),r.score(),r.comment(),a.userId());return ApiResponse.success(r.orderId(),"Đã lưu đánh giá");}
 @GetMapping("/suppliers/{id}/ratings") public ApiResponse<?> ratings(@AuthenticationPrincipal Actor a,@PathVariable long id){return ApiResponse.success(jdbc.queryForMap("SELECT supplier_id,COUNT(*) rating_count,ROUND(AVG(score),2) average_score FROM supplier_ratings WHERE supplier_id=? GROUP BY supplier_id",id),"Chất lượng nhà cung cấp");}
 public record Incident(@NotBlank @Pattern(regexp="DAMAGED|LOST") String type,@NotNull @DecimalMin("0") BigDecimal fee,@NotBlank @Size(max=1000) String description){}
 @PostMapping("/assets/{id}/incidents") @Transactional public ApiResponse<?> incident(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Incident r){a.requireRole("ASSET_MANAGER","OPERATIONS_COORDINATOR");var asset=jdbc.queryForMap("SELECT * FROM returnable_assets WHERE asset_id=? FOR UPDATE",id);long incident=sql.insert("INSERT INTO asset_incidents(asset_id,incident_type,fee_amount,description,reported_by) VALUES (?,?,?,?,?)",id,r.type(),r.fee(),r.description(),a.userId());jdbc.update("UPDATE returnable_assets SET status=?,condition_status=? WHERE asset_id=?",r.type(),"LOST".equals(r.type())?"UNUSABLE":"MAJOR_DAMAGE",id);jdbc.update("INSERT INTO asset_movements(asset_id,movement_type,recorded_by,note) VALUES (?,?,?,?)",id,r.type(),a.userId(),r.description());return ApiResponse.success(incident,"Đã ghi nhận sự cố thùng");}
 @GetMapping("/assets/inventory") public ApiResponse<?> inventory(@AuthenticationPrincipal Actor a){a.requireRole("ASSET_MANAGER","OPERATIONS_COORDINATOR");return ApiResponse.success(jdbc.queryForList("SELECT status,condition_status,current_organization_id,COUNT(*) quantity FROM returnable_assets GROUP BY status,condition_status,current_organization_id ORDER BY status,condition_status"),"Kiểm kê thùng");}
}
