"""Build the standalone MySQL installer from the backend's Flyway migrations."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = ROOT / "backend/src/main/resources/db/migration"
files = sorted(MIGRATIONS.glob("V*__*.sql"), key=lambda p: int(p.name.split("__")[0][1:]))
version = int(files[-1].name.split("__")[0][1:])
header = f"""-- FreshLink standalone MySQL installer (MySQL 8.4).
-- Generated by: python database/build_sql.py -- do not edit manually.
-- Includes schema and reference/catalogue seed data through Flyway V{version}.
-- Run ONCE on a NEW/EMPTY database. This is not an upgrade or a data backup.
-- No DROP statements; do not use --force or continue after an import error.
-- For a managed database without CREATE DATABASE permission, omit the following
-- CREATE DATABASE and USE statements and select the provider's empty database.
-- After a successful full import, start the backend ONCE with:
-- SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
-- SPRING_FLYWAY_BASELINE_VERSION={version}
-- Then remove these two environment variables. Keep Flyway enabled.
-- See database/README.md for local, Docker, cloud and account setup.

CREATE DATABASE IF NOT EXISTS freshlink_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE freshlink_db;
SET NAMES utf8mb4;
SET time_zone = '+00:00';

"""
parts = [header]
for migration in files:
    parts.append(f"-- ===== BEGIN {migration.name} =====\n")
    parts.append(migration.read_text(encoding="utf-8").rstrip() + "\n")
    parts.append(f"-- ===== END {migration.name} =====\n\n")
parts.append("SELECT 'FreshLink schema and reference data imported successfully' AS result;\n")
output = "".join(parts)
target = ROOT / "database/freshlink_mysql_database.sql"
target.write_text(output, encoding="utf-8", newline="\n")
print(f"Generated {target.name}: V1-V{version}, {len(re.findall(r'CREATE TABLE ', output))} tables")
