package vn.freshlink.quality;
import java.time.Instant;import java.util.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import vn.freshlink.common.*;import vn.freshlink.common.api.ApiResponse;import vn.freshlink.identity.Actor;
@RestController @RequestMapping("/api/batches") public class BatchDocumentRequestController{
 private final JdbcTemplate jdbc;private final Sql sql;private final MediaController media;public BatchDocumentRequestController(JdbcTemplate j,Sql s,MediaController m){jdbc=j;sql=s;media=m;}
 public record Create(@NotBlank @Pattern(regexp="BUSINESS_LICENSE|FOOD_SAFETY|VIETGAP|ORIGIN_PROOF|OTHER") String documentType,@NotBlank @Size(max=1000) String message,Instant dueAt){}
 public record Submit(@NotNull Long fileId,@NotBlank @Size(max=1000) String note){}
 public record Review(boolean accepted,@NotBlank @Size(max=1000) String note){}
 @GetMapping("/{id}/document-requests") public ApiResponse<?> list(@AuthenticationPrincipal Actor a,@PathVariable long id){var b=jdbc.queryForMap("SELECT supplier_id FROM batches WHERE batch_id=?",id);if(!a.hasRole("QUALITY_INSPECTOR")&&!a.hasRole("OPERATIONS_COORDINATOR")&&!a.hasRole("SYSTEM_ADMIN"))a.requireOrganization(((Number)b.get("supplier_id")).longValue(),"SUPPLIER_MANAGER","SUPPLIER_STAFF");return ApiResponse.success(jdbc.queryForList("SELECT r.*,f.original_name FROM batch_document_requests r LEFT JOIN media_files f ON f.file_id=r.submitted_file_id WHERE r.batch_id=? ORDER BY r.created_at DESC",id),"Yêu cầu hồ sơ");}
 @PostMapping("/{id}/document-requests") @Transactional public ApiResponse<?> create(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Create r){a.requireRole("QUALITY_INSPECTOR");var b=jdbc.queryForMap("SELECT supplier_id,batch_code FROM batches WHERE batch_id=?",id);if(r.dueAt()!=null&&!r.dueAt().isAfter(Instant.now()))throw new IllegalArgumentException("Hạn bổ sung phải ở tương lai");long request=sql.insert("INSERT INTO batch_document_requests(batch_id,document_type,message,due_at,requested_by) VALUES (?,?,?,?,?)",id,r.documentType(),r.message(),r.dueAt()==null?null:java.sql.Timestamp.from(r.dueAt()),a.userId());jdbc.update("INSERT INTO notifications(user_id,notification_type,title,message,related_entity_type,related_entity_id) SELECT DISTINCT m.user_id,'BATCH_DOCUMENT_REQUEST',CONCAT('Lô ',?,' cần bổ sung hồ sơ'),?,'BATCH',? FROM organization_members m WHERE m.organization_id=? AND m.status='ACTIVE'",b.get("batch_code"),r.message(),id,b.get("supplier_id"));return ApiResponse.success(request,"Đã yêu cầu bổ sung hồ sơ");}
 @PostMapping("/document-requests/{requestId}/submit") @Transactional public ApiResponse<?> submit(@AuthenticationPrincipal Actor a,@PathVariable long requestId,@jakarta.validation.Valid @RequestBody Submit r){var x=jdbc.queryForMap("SELECT r.*,b.supplier_id FROM batch_document_requests r JOIN batches b ON b.batch_id=r.batch_id WHERE r.document_request_id=? FOR UPDATE",requestId);a.requireOrganization(((Number)x.get("supplier_id")).longValue(),"SUPPLIER_MANAGER","SUPPLIER_STAFF");if(!Set.of("OPEN","REJECTED").contains(x.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Yêu cầu không chờ bổ sung");media.requireOwned(a,r.fileId());jdbc.update("UPDATE batch_document_requests SET status='SUBMITTED',submitted_file_id=?,supplier_note=? WHERE document_request_id=?",r.fileId(),r.note(),requestId);return ApiResponse.success(requestId,"Đã gửi hồ sơ bổ sung");}
 @PostMapping("/document-requests/{requestId}/review") @Transactional public ApiResponse<?> review(@AuthenticationPrincipal Actor a,@PathVariable long requestId,@jakarta.validation.Valid @RequestBody Review r){a.requireRole("QUALITY_INSPECTOR");var x=jdbc.queryForMap("SELECT r.*,b.supplier_id,b.batch_code FROM batch_document_requests r JOIN batches b ON b.batch_id=r.batch_id WHERE r.document_request_id=? FOR UPDATE",requestId);if(!"SUBMITTED".equals(x.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Hồ sơ chưa được gửi");jdbc.update("UPDATE batch_document_requests SET status=?,message=CONCAT(message,' | Phản hồi: ',?),reviewed_by=?,reviewed_at=UTC_TIMESTAMP(3) WHERE document_request_id=?",r.accepted()?"ACCEPTED":"REJECTED",r.note(),a.userId(),requestId);jdbc.update("INSERT INTO notifications(user_id,notification_type,title,message,related_entity_type,related_entity_id) SELECT DISTINCT m.user_id,'BATCH_DOCUMENT_REVIEW',CONCAT('Phản hồi hồ sơ lô ',?),?,'BATCH',? FROM organization_members m WHERE m.organization_id=? AND m.status='ACTIVE'",x.get("batch_code"),r.note(),x.get("batch_id"),x.get("supplier_id"));return ApiResponse.success(requestId,r.accepted()?"Đã chấp nhận hồ sơ":"Đã yêu cầu bổ sung lại");}
}
