package vn.freshlink.quality;
import java.math.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import vn.freshlink.common.api.ApiResponse;import vn.freshlink.identity.Actor;
@RestController @RequestMapping("/api/batches") public class BatchManagementController{
 private final JdbcTemplate jdbc;public BatchManagementController(JdbcTemplate j){jdbc=j;}
 public record Update(@NotNull @DecimalMin("0.001") @Digits(integer=9,fraction=3) BigDecimal quantity,@NotBlank @Size(max=1000) String origin){}
 public record Reason(@NotBlank @Size(max=500) String reason){}
 private java.util.Map<String,Object> lock(long id){var xs=jdbc.queryForList("SELECT * FROM batches WHERE batch_id=? FOR UPDATE",id);if(xs.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy lô");return xs.get(0);}
 @PutMapping("/{id}") @Transactional public ApiResponse<?> update(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Update r){var b=lock(id);a.requireOrganization(((Number)b.get("supplier_id")).longValue(),"SUPPLIER_MANAGER","SUPPLIER_STAFF");if(!"CREATED".equals(b.get("batch_status"))||b.get("received_at")!=null)throw new ResponseStatusException(HttpStatus.CONFLICT,"Gate đã tiếp nhận, không thể sửa lô");BigDecimal other=jdbc.queryForObject("SELECT COALESCE(SUM(declared_quantity),0) FROM batches WHERE supply_request_item_id=? AND batch_id<>? AND batch_status<>'CLOSED'",BigDecimal.class,b.get("supply_request_item_id"),id),accepted=jdbc.queryForObject("SELECT accepted_quantity FROM supply_request_items WHERE supply_request_item_id=?",BigDecimal.class,b.get("supply_request_item_id"));if(other.add(r.quantity()).compareTo(accepted)>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Tổng lượng lô vượt lượng cung ứng đã nhận");jdbc.update("UPDATE batches SET declared_quantity=?,trace_note=? WHERE batch_id=?",r.quantity(),r.origin(),id);return ApiResponse.success(id,"Đã cập nhật lô");}
 @PostMapping("/{id}/cancel") @Transactional public ApiResponse<?> cancel(@AuthenticationPrincipal Actor a,@PathVariable long id,@jakarta.validation.Valid @RequestBody Reason r){var b=lock(id);a.requireOrganization(((Number)b.get("supplier_id")).longValue(),"SUPPLIER_MANAGER","SUPPLIER_STAFF");if(!"CREATED".equals(b.get("batch_status"))||b.get("received_at")!=null)throw new ResponseStatusException(HttpStatus.CONFLICT,"Gate đã tiếp nhận, không thể hủy lô");jdbc.update("UPDATE batches SET batch_status='CLOSED',trace_note=CONCAT(COALESCE(trace_note,''),' | CANCELLED: ',?) WHERE batch_id=?",r.reason(),id);return ApiResponse.success(id,"Đã hủy lô");}
}
