package vn.freshlink.billing;
import java.math.*;import java.time.*;import jakarta.validation.constraints.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import vn.freshlink.common.*;import vn.freshlink.common.api.ApiResponse;import vn.freshlink.identity.Actor;
@RestController @RequestMapping("/api/billing/invoices") public class InvoiceController{
 private final JdbcTemplate jdbc;private final Sql sql;public InvoiceController(JdbcTemplate j,Sql s){jdbc=j;sql=s;}
 public record Create(@NotNull Long orderId,@NotNull LocalDate dueDate,@NotNull @DecimalMin("0") @Digits(integer=13,fraction=2) BigDecimal taxAmount,@Size(max=500) String note){}
 @PostMapping @Transactional public ApiResponse<?> create(@AuthenticationPrincipal Actor a,@jakarta.validation.Valid @RequestBody Create r){a.requireRole("ACCOUNTANT");var o=jdbc.queryForMap("SELECT * FROM customer_orders WHERE order_id=? FOR UPDATE",r.orderId());if(r.dueDate().isBefore(LocalDate.now()))throw new IllegalArgumentException("Hạn thanh toán không được ở quá khứ");BigDecimal subtotal=(BigDecimal)o.get("total_amount"),total=subtotal.add(r.taxAmount()).setScale(2,RoundingMode.HALF_UP);long id=sql.insert("INSERT INTO invoices(invoice_code,order_id,restaurant_id,due_date,subtotal_amount,tax_amount,total_amount,note,created_by) VALUES (?,?,?,?,?,?,?,?,?)","INV-"+java.util.UUID.randomUUID().toString().substring(0,24),r.orderId(),o.get("restaurant_id"),r.dueDate(),subtotal,r.taxAmount(),total,r.note(),a.userId());return ApiResponse.success(id,"Đã phát hành hóa đơn");}
 @GetMapping public ApiResponse<?> list(@AuthenticationPrincipal Actor a,@RequestParam(required=false) Long restaurantId,@RequestParam(required=false) Boolean overdue){String q="SELECT i.*,COALESCE((SELECT SUM(CASE WHEN p.payment_type='REFUND' THEN -p.amount ELSE p.amount END) FROM payments p WHERE p.order_id=i.order_id AND p.status='CONFIRMED'),0) paid_amount,i.total_amount-COALESCE((SELECT SUM(CASE WHEN p.payment_type='REFUND' THEN -p.amount ELSE p.amount END) FROM payments p WHERE p.order_id=i.order_id AND p.status='CONFIRMED'),0) balance_amount FROM invoices i WHERE 1=1";java.util.List<Object> args=new java.util.ArrayList<>();if(restaurantId!=null){a.requireOrganization(restaurantId,"RESTAURANT_MANAGER");q+=" AND i.restaurant_id=?";args.add(restaurantId);}else a.requireRole("ACCOUNTANT");if(Boolean.TRUE.equals(overdue))q+=" AND i.due_date<CURRENT_DATE AND i.status NOT IN ('PAID','VOID')";return ApiResponse.success(jdbc.queryForList(q+" ORDER BY i.due_date DESC,i.invoice_id DESC LIMIT 500",args.toArray()),"Hóa đơn và công nợ");}
 @PostMapping("/refresh-overdue") @Transactional public ApiResponse<?> refresh(@AuthenticationPrincipal Actor a){a.requireRole("ACCOUNTANT");int n=jdbc.update("UPDATE invoices SET status='OVERDUE' WHERE due_date<CURRENT_DATE AND status IN ('ISSUED','PARTIALLY_PAID')");return ApiResponse.success(n,"Đã cập nhật công nợ quá hạn");}
 @GetMapping("/report") public org.springframework.http.ResponseEntity<String> report(@AuthenticationPrincipal Actor a,@RequestParam LocalDate from,@RequestParam LocalDate to){a.requireRole("ACCOUNTANT");if(to.isBefore(from)||java.time.temporal.ChronoUnit.DAYS.between(from,to)>366)throw new IllegalArgumentException("Khoảng báo cáo không hợp lệ");var rows=jdbc.queryForList("SELECT invoice_code,order_id,restaurant_id,issued_at,due_date,total_amount,status FROM invoices WHERE DATE(issued_at) BETWEEN ? AND ? ORDER BY issued_at",from,to);StringBuilder csv=new StringBuilder("invoice_code,order_id,restaurant_id,issued_at,due_date,total_amount,status\n");for(var x:rows)csv.append(x.get("invoice_code")).append(',').append(x.get("order_id")).append(',').append(x.get("restaurant_id")).append(',').append(x.get("issued_at")).append(',').append(x.get("due_date")).append(',').append(x.get("total_amount")).append(',').append(x.get("status")).append('\n');return org.springframework.http.ResponseEntity.ok().header("Content-Type","text/csv;charset=UTF-8").header("Content-Disposition","attachment; filename=invoices.csv").body(csv.toString());}
}
