import { useState } from 'react'
import { Alert, Button, Card, Form, Input, List } from 'antd'
import { Link, useLocation } from 'react-router-dom'
import { api } from '../api/http'
import { display } from '../components/permissions'
import type { Row } from '../components/Workspace'

export default function AccessPage(){
 const location=useLocation();const mode=location.pathname;const token=new URLSearchParams(location.hash.slice(1)||location.search).get('token')??'';const [error,setError]=useState('');const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);const [rows,setRows]=useState<Row[]>([])
 const invitation=mode==='/accept-invitation';const reset=mode==='/reset-password';const status=mode==='/registration-status';const title=invitation?'Tham gia đơn vị':reset?'Đặt lại mật khẩu':status?'Theo dõi đăng ký':'Khôi phục mật khẩu'
 return <main className="public-form"><Card title={title}>{error&&<Alert type="error" message={error}/>} {done&&<Alert type="success" message={status?'Đã tra cứu trạng thái':invitation?'Đã tham gia đơn vị. Hãy đăng nhập.':reset?'Đã đổi mật khẩu. Hãy đăng nhập lại.':'Nếu tài khoản hợp lệ, hướng dẫn sẽ được gửi qua email.'}/>}<Form layout="vertical" initialValues={{token}} onFinish={async v=>{setBusy(true);setError('');try{const result=await api<Row[]>(invitation?'/public/invitations/accept':reset?'/public/auth/reset-password':status?'/public/partners/status':'/public/auth/forgot-password','POST',v);if(status)setRows(result);setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{(invitation||reset)&&<Form.Item name="token" hidden rules={[{required:true}]}><Input/></Form.Item>}{!invitation&&!reset&&<Form.Item name="email" label="Email" rules={[{required:true,type:'email'}]}><Input autoComplete="email"/></Form.Item>}{invitation&&<><Form.Item name="fullName" label="Họ tên" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="phone" label="Điện thoại"><Input/></Form.Item><Alert type="info" message="Nếu email đã có tài khoản, nhập mật khẩu hiện tại. Nếu chưa có, tạo mật khẩu ít nhất 12 ký tự."/></>}{(invitation||reset||status)&&<Form.Item name="password" label={status?'Mật khẩu khi đăng ký':'Mật khẩu'} rules={[{required:true},...(reset?[{min:12}]:[])]}><Input.Password autoComplete={status?'current-password':'new-password'}/></Form.Item>}<Button type="primary" loading={busy} htmlType="submit">{status?'Tra cứu':'Gửi'}</Button></Form><List dataSource={rows} renderItem={r=><List.Item>{String(r.organization_name)} · {display(r.status)}<p>{String(r.review_note??'')}</p></List.Item>}/><p><Link to="/login">Đăng nhập</Link> · <Link to="/register">Đăng ký hợp tác</Link></p></Card></main>
}
