import { useState } from 'react'
import { Alert, Button, Card, Input, Space, Table } from 'antd'
import { api } from '../api/http'
import { ActionForm, DataTable, options, tomorrow, type Row, useRows } from '../components/Workspace'

export function OffersEditor({organizationId,catalog}:{organizationId:number;catalog:Row[]}){
 const [selected,setSelected]=useState<Row>();const [date,setDate]=useState(tomorrow());const [from,setFrom]=useState('');const [rows,setRows]=useState<Row[]>([]);const [result,setResult]=useState<Row[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [key,setKey]=useState(crypto.randomUUID());const offers=useRows('/supplier/offers?supplierId='+organizationId)
 async function run(dryRun:boolean){setBusy(true);setError('');try{setResult(await api<Row[]>('/supplier/offers/bulk','POST',{items:rows,dryRun},key));if(!dryRun){await offers.refetch();window.dispatchEvent(new Event('freshlink:saved'))}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><ActionForm title="Năng lực cung ứng" path="/supplier/offers" fields={[{name:'skuId',label:'Sản phẩm',type:'select',options:options(catalog,'sku_id','sku_name')},{name:'date',label:'Ngày có hàng',type:'date',initial:tomorrow()},{name:'quantity',label:'Số lượng',type:'number',min:0.001},{name:'price',label:'Đơn giá',type:'number'}]} transform={v=>({...v,supplierId:organizationId})} onDone={()=>void offers.refetch()}/><DataTable path={'/supplier/offers?supplierId='+organizationId} rowKey="supplier_offer_id" columns={[[ 'sku_name','Sản phẩm'],['available_date','Ngày'],['available_quantity','Năng lực'],['reserved_quantity','Đã giữ'],['supplier_unit_price','Đơn giá'],['status','Trạng thái']]} actions={r=><Button onClick={()=>setSelected(r)}>Sửa</Button>}/>{selected&&<ActionForm key={String(selected.supplier_offer_id)} title={'Sửa '+selected.sku_name} method="PUT" path={'/supplier/offers/'+selected.supplier_offer_id} fields={[{name:'quantity',label:'Số lượng (không dưới lượng đã giữ)',type:'number',min:Math.max(0.001,Number(selected.reserved_quantity)),initial:selected.available_quantity},{name:'price',label:'Đơn giá (không đổi nếu đã giữ)',type:'number',initial:selected.supplier_unit_price}]} onDone={()=>setSelected(undefined)}/>}
 <Card title="Sao chép hoặc nhập Excel"><p>File .xlsx, trang đầu tiên có các cột: skuCode, date (YYYY-MM-DD), quantity, price. Tối đa 300 dòng và 2 MB. Kiểm tra bản xem trước trước khi ghi.</p>{error&&<Alert type="error" message={error}/>}<Space wrap><label>Ngày/đầu tuần nguồn<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Ngày/đầu tuần đích<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{[1,7].map(days=><Button key={days} disabled={!from||!date} onClick={()=>{const offset=(Date.parse(date)-Date.parse(from))/86400000;const batch=(offers.data??[]).filter(x=>String(x.available_date)>=from&&Date.parse(String(x.available_date))<Date.parse(from)+days*86400000).map(x=>({supplierId:organizationId,skuId:x.sku_id,date:new Date(Date.parse(String(x.available_date))+offset*86400000).toISOString().slice(0,10),quantity:x.available_quantity,price:x.supplier_unit_price}));setRows(batch);setResult([]);setKey(crypto.randomUUID())}}>Sao chép {days===1?'ngày':'tuần'}</Button>)}</Space><Input type="file" accept=".xlsx" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('');setRows([]);setResult([]);try{if(file.size>2*1024*1024)throw new Error('File tối đa 2 MB');const ExcelJS=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const sheet=wb.worksheets[0];if(!sheet||sheet.rowCount>301)throw new Error('Chỉ nhận tối đa 300 dòng dữ liệu');const headers=['skuCode','date','quantity','price'];headers.forEach((h,i)=>{if(sheet.getRow(1).getCell(i+1).text.trim()!==h)throw new Error('Cột '+(i+1)+' phải là '+h)});const imported:Row[]=[];sheet.eachRow((r,i)=>{if(i===1)return;const sku=catalog.find(x=>x.sku_code===r.getCell(1).text.trim());const raw=r.getCell(2).value;const d=raw instanceof Date?raw.toISOString().slice(0,10):r.getCell(2).text.trim();if(!sku)throw new Error('Dòng '+i+': SKU không tồn tại');if(!/^\d{4}-\d{2}-\d{2}$/.test(d))throw new Error('Dòng '+i+': ngày không hợp lệ');imported.push({supplierId:organizationId,skuId:sku.sku_id,date:d,quantity:Number(r.getCell(3).value),price:Number(r.getCell(4).value)})});setRows(imported);setKey(crypto.randomUUID())}catch(err){setError((err as Error).message)}}}/>
 {rows.length>0&&<><Table<Row> rowKey={(_,i)=>String(i)} dataSource={rows} columns={[{title:'Sản phẩm',render:(_,r)=>String(catalog.find(x=>x.sku_id===r.skuId)?.sku_name??'')},{title:'Ngày',dataIndex:'date'},{title:'Số lượng',dataIndex:'quantity'},{title:'Giá',dataIndex:'price'}]}/><Space><Button loading={busy} onClick={()=>void run(true)}>Kiểm tra từng dòng</Button><Button type="primary" loading={busy} disabled={!result.length||result.some(r=>!r.success)||result.some(r=>Number(r.id)>0)} onClick={()=>void run(false)}>Xác nhận nhập</Button></Space></>}{result.map(r=><Alert key={String(r.row)} type={r.success?'success':'error'} message={'Dòng '+r.row+': '+(r.success?(Number(r.id)>0?'Đã nhập':'Hợp lệ'):r.message)}/>)}</Card></>
}
