import { useState } from 'react'
import { Alert, Button, Card, Input, InputNumber, Select, Space, Table } from 'antd'
import { Link } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/http'
import { options, type Row, useRows } from '../components/Workspace'

export function SourcingWorkbench({date}:{date:string}){
 const demand=useRows('/operations/demand?date='+date);const offers=useRows('/operations/offers?date='+date);const batches=useRows('/batches');const lookup=useQuery({queryKey:['lookup'],queryFn:()=>api<{addresses:Row[]}>('/operations/lookup')});const client=useQueryClient()
 const [dock,setDock]=useState<number>();const [arrival,setArrival]=useState('05:00');const [commission,setCommission]=useState(0);const [selected,setSelected]=useState<Row>();const [source,setSource]=useState<number>();const [quantity,setQuantity]=useState(1);const [queue,setQueue]=useState<Row[]>([]);const [kind,setKind]=useState<'source'|'allocate'>('source');const [results,setResults]=useState<Row[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [key,setKey]=useState(crypto.randomUUID())
 const matching=(offers.data??[]).filter(o=>o.sku_id===selected?.sku_id).sort((a,b)=>Number(a.supplier_unit_price)-Number(b.supplier_unit_price)||Number(b.quality_rate??0)-Number(a.quality_rate??0))
 function stage(mode:'source'|'allocate',rows:Row[]){setKind(mode);setQueue(rows);setResults([]);setKey(crypto.randomUUID())}
 async function send(){setBusy(true);setError('');try{setResults(await api<Row[]>(kind==='source'?'/operations/supply-requests/bulk':'/allocations/bulk','POST',{items:queue},key));await client.invalidateQueries();window.dispatchEvent(new Event('freshlink:saved'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function suggest(mode:'source'|'allocate'){
  if(mode==='source'&&!dock){setError('Chọn điểm Gate');return}setError('');const proposed:Row[]=[];const used=new Map<number,number>()
  for(const d of demand.data??[]){let needed=Number(d.confirmed_quantity)-Number(mode==='source'?d.sourced_quantity:d.allocated_quantity??0);const candidates=mode==='source'?(offers.data??[]).filter(x=>x.sku_id===d.sku_id).sort((a,b)=>Number(a.supplier_unit_price)-Number(b.supplier_unit_price)):(batches.data??[]).filter(x=>x.sku_id===d.sku_id&&['ACCEPTED','PARTIALLY_ACCEPTED'].includes(String(x.batch_status)))
   for(const c of candidates){if(needed<=0)break;const id=Number(mode==='source'?c.supplier_offer_id:c.batch_id);const available=Number(mode==='source'?c.available_quantity:c.accepted_quantity)-Number(mode==='source'?c.reserved_quantity:c.allocated_quantity)-(used.get(id)??0);const q=Math.min(needed,available);if(q<=0)continue;proposed.push(mode==='source'?{offerId:id,orderItemId:d.order_item_id,crossDockId:dock,arrivalTime:arrival,quantity:q,commissionRate:commission}:{batchId:id,orderItemId:d.order_item_id,quantity:q});used.set(id,(used.get(id)??0)+q);needed-=q}
  }stage(mode,proposed.slice(0,100))
 }
 return <>{[demand.error,offers.error,batches.error,lookup.error].filter(Boolean).map((e,i)=><Alert key={i} type="error" message={e?.message}/>)}{error&&<Alert type="error" message={error}/>}<Card title="Nhu cầu và lượng còn thiếu"><Table<Row> rowKey="order_item_id" dataSource={demand.data} loading={demand.isPending} columns={[{title:'Đơn',render:(_,r)=><Link to={'/portal/orders/'+r.order_id}>{String(r.order_code)}</Link>},{title:'Sản phẩm',dataIndex:'sku_name'},{title:'Cần',dataIndex:'confirmed_quantity'},{title:'Nguồn dự kiến (gồm cách ly)',dataIndex:'sourced_quantity'},{title:'Đã chia',dataIndex:'allocated_quantity'},{title:'Thiếu nguồn',render:(_,r)=>Math.max(0,Number(r.confirmed_quantity)-Number(r.sourced_quantity))},{title:'Thao tác',render:(_,r)=><Button onClick={()=>{setSelected(r);setSource(undefined);setQuantity(Math.max(0,Number(r.confirmed_quantity)-Number(r.sourced_quantity)))}}>Chọn nguồn</Button>}]}/></Card>
 <Card title="Chuẩn bị yêu cầu"><Space wrap><Select style={{minWidth:190}} placeholder="Điểm Gate" value={dock} options={options(lookup.data?.addresses.filter(a=>a.address_type==='CROSS_DOCK'),'address_id','address_name')} onChange={v=>setDock(Number(v))}/><Input type="time" value={arrival} onChange={e=>setArrival(e.target.value)}/><label>Hoa hồng %<InputNumber min={0} max={100} value={commission} onChange={v=>setCommission(v??0)}/></label></Space><p>Gợi ý chỉ sử dụng nguồn đúng sản phẩm/ngày, còn lượng; ưu tiên giá thấp. Chất lượng lịch sử hiển thị để điều phối kiểm tra trước khi giữ nguồn.</p><Space wrap><Button onClick={()=>suggest('source')}>Gợi ý phân nguồn hàng loạt</Button><Button onClick={()=>suggest('allocate')}>Gợi ý chia lô đạt hàng loạt</Button></Space>{selected&&<><h4>{String(selected.order_code)} · {String(selected.sku_name)}</h4><Select style={{width:'100%'}} placeholder="Nguồn phù hợp" value={source} options={matching.map(o=>({value:Number(o.supplier_offer_id),label:String(o.organization_name)+' · còn '+(Number(o.available_quantity)-Number(o.reserved_quantity))+' · '+Number(o.supplier_unit_price).toLocaleString('vi-VN')+' đ · QC '+(o.quality_rate==null?'chưa có dữ liệu':o.quality_rate+'%')}))} onChange={setSource}/><Space><InputNumber min={0.001} value={quantity} onChange={v=>setQuantity(v??0)}/><Button disabled={!source||!dock||quantity<=0} onClick={()=>stage('source',[{orderItemId:selected.order_item_id,offerId:source,crossDockId:dock,arrivalTime:arrival,quantity,commissionRate:commission}])}>Đưa vào bản xem trước</Button></Space></>}</Card>
 {queue.length>0&&<Card title={kind==='source'?'Xem trước phân nguồn':'Xem trước chia hàng đạt'}><Table<Row> rowKey={(_,i)=>String(i)} dataSource={queue} columns={[{title:'Đơn / sản phẩm',render:(_,r)=>{const d=demand.data?.find(x=>x.order_item_id===r.orderItemId);return String(d?.order_code)+' · '+String(d?.sku_name)}},{title:'Nguồn / lô',render:(_,r)=>String(kind==='source'?offers.data?.find(x=>x.supplier_offer_id===r.offerId)?.organization_name:batches.data?.find(x=>x.batch_id===r.batchId)?.batch_code)},{title:'Số lượng',dataIndex:'quantity'}]}/><Button type="primary" loading={busy} disabled={results.some(r=>r.success)} onClick={()=>void send()}>Xác nhận {queue.length} dòng</Button>{results.map(r=><Alert key={String(r.row)} type={r.success?'success':'error'} message={'Dòng '+r.row+': '+(r.success?'Đã lưu':r.message)}/>)}{results.some(r=>!r.success)&&<Alert type="info" message="Tải lại gợi ý cho những dòng còn thiếu; dòng thành công đã được giữ và không thực hiện lại."/>}</Card>}</>
}
