import { useState } from 'react'
import { Alert, Button, Card, Input, InputNumber, Select, Space, Table } from 'antd'
import { api } from '../api/http'
import { useRows, options, type Row } from '../components/Workspace'

export function WeeklyEditor({organizationId,catalog,onPrepare}:{organizationId:number;catalog:Row[];onPrepare:(date:string,plan:number,lines:Row[])=>void}){
 const [week,setWeek]=useState('');const [lines,setLines]=useState<{skuId?:number;date:string;quantity:number}[]>([{date:'',quantity:1}]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const q=useRows('/weekly-plans?restaurantId='+organizationId)
 function addDays(d:string,n:number){const v=new Date(d+'T00:00:00Z');v.setUTCDate(v.getUTCDate()+n);return v.toISOString().slice(0,10)}
 return <><Card title="Nhu cầu tuần"><Alert type="info" message="Kế hoạch là nhu cầu dự kiến; chuẩn bị và xác nhận đơn ngày riêng để chốt."/><Space wrap><label>Thứ Hai đầu tuần<Input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label><Button disabled={!week||!q.data?.length} onClick={()=>{const previous=addDays(week,-7);const old=q.data?.filter(x=>x.week_start_date===previous)??[];setLines(old.map(x=>({skuId:Number(x.sku_id),date:addDays(String(x.demand_date),7),quantity:Number(x.planned_quantity)})));if(!old.length)setError('Tuần trước chưa có kế hoạch')}}>Sao chép tuần trước</Button></Space>{error&&<Alert type="error" message={error}/>}{lines.map((l,i)=><Space wrap key={i} style={{display:'flex',margin:'12px 0'}}><Select style={{width:220}} placeholder="Sản phẩm" value={l.skuId} options={options(catalog,'sku_id','sku_name')} onChange={v=>setLines(xs=>xs.map((x,j)=>j===i?{...x,skuId:Number(v)}:x))}/><Input type="date" value={l.date} onChange={e=>setLines(xs=>xs.map((x,j)=>j===i?{...x,date:e.target.value}:x))}/><InputNumber min={0.001} value={l.quantity} onChange={v=>setLines(xs=>xs.map((x,j)=>j===i?{...x,quantity:v??1}:x))}/><Button onClick={()=>setLines(xs=>xs.filter((_,j)=>i!==j))}>Bỏ dòng</Button></Space>)}<Space><Button onClick={()=>setLines([...lines,{date:week,quantity:1}])}>Thêm dòng</Button><Button type="primary" loading={busy} disabled={!week||!lines.length||lines.some(x=>!x.skuId||!x.date)} onClick={async()=>{setBusy(true);setError('');try{if(new Date(week+'T00:00:00Z').getUTCDay()!==1)throw new Error('Chọn thứ Hai đầu tuần');if(new Set(lines.map(x=>x.date+':'+x.skuId)).size!==lines.length)throw new Error('Không lặp sản phẩm trong cùng ngày');await api('/weekly-plans','POST',{restaurantId:organizationId,weekStart:week,items:lines});await q.refetch();window.dispatchEvent(new Event('freshlink:saved'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Lưu kế hoạch</Button></Space></Card><Table<Row> rowKey="weekly_plan_item_id" dataSource={q.data} columns={[{title:'Sản phẩm',dataIndex:'sku_name'},{title:'Ngày',dataIndex:'demand_date'},{title:'Số lượng',dataIndex:'planned_quantity'},{title:'Trạng thái',dataIndex:'status'},{title:'Thao tác',render:(_,r)=>r.converted_order_item_id==null&&<Button onClick={()=>onPrepare(String(r.demand_date),Number(r.weekly_plan_id),q.data?.filter(x=>x.weekly_plan_id===r.weekly_plan_id&&x.demand_date===r.demand_date)??[])}>Chuẩn bị đơn ngày</Button>}]}/></>
}
