import { useState } from 'react'
import { Alert, Button, Card, Descriptions, Empty, Input, List, Space, Statistic, Tabs, Timeline } from 'antd'
import { Link, useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { useAuth } from '../auth/AuthContext'
import { api } from '../api/http'
import { ActionForm, DataTable, EvidenceLink, QrButton, type Row, useRows } from '../components/Workspace'
import { can, display, roleNames } from '../components/permissions'
import { useUrlTab } from '../components/useUrlTab'
import { OrderDetail } from './TripPage'
import TripPage from './TripPage'
import OperationsPage from './OperationsPage'
import { SystemCheckPage } from './ManagementPages'

export function DashboardPage(){
 const q=useRows('/workspace/tasks');const {membership}=useAuth()
 return <><p>Công việc theo đơn vị và quyền đang chọn. Mở từng mục để xử lý.</p>{can(membership,'RESTAURANT_MANAGER','RESTAURANT_PURCHASER')&&membership?.organizationType==='RESTAURANT'&&<Link className="button button-small" to="/portal/orders/new">Đặt hàng mới</Link>}{q.error&&<Alert type="error" message={q.error.message} action={<Button onClick={()=>void q.refetch()}>Thử lại</Button>}/>}<div className="stat-grid">{q.data?.map(x=><Card key={String(x.title)} loading={q.isPending}><Statistic title={String(x.title)} value={Number(x.count)}/><Link to={String(x.url)}>Mở công việc →</Link></Card>)}</div>{q.data?.length===0&&<Empty description="Chưa có công việc đang chờ"/>}</>
}
export function AccountPage(){const {discardSession}=useAuth();return <ActionForm title="Đổi mật khẩu" path="/auth/change-password" fields={[{name:'currentPassword',label:'Mật khẩu hiện tại',type:'password'},{name:'newPassword',label:'Mật khẩu mới (12–72 ký tự, tối đa 72 byte)',type:'password'}]} onDone={discardSession}/>}

export function DetailPage({type,id}:{type:string;id:number}){
 if(type==='orders')return <OrderDetail orderId={id}/>
 if(type==='trips')return <TripPage initialSelected={id}/>
 if(type==='batches')return <BatchDetail id={id}/>
 return <RecordDetail type={type} id={id}/>
}
function RecordDetail({type,id}:{type:string;id:number}){
 const path=type==='settlements'?`/workspace/settlements/${id}`:`/${type}/${id}`;const q=useQuery({queryKey:[path],queryFn:()=>api<Row>(path)})
 const fields=type==='settlements'?['settlement_code','payable_amount','status','paid_at','external_reference']:['complaint_code','description','status','final_resolution','submitted_at']
 return <Card title={type==='settlements'?'Chi tiết đối soát':'Chi tiết khiếu nại'} loading={q.isPending}>{q.error&&<Alert type="error" message={q.error.message}/>}<Descriptions column={1} items={fields.map(k=>({key:k,label:({settlement_code:'Mã phiếu',payable_amount:'Phải trả',status:'Trạng thái',paid_at:'Ngày thanh toán',external_reference:'Chứng từ',complaint_code:'Mã khiếu nại',description:'Nội dung',final_resolution:'Phương án',submitted_at:'Ngày gửi'} as Record<string,string>)[k],children:display(q.data?.[k],k)}))}/><List dataSource={q.data?.items as Row[]??[]} renderItem={x=><List.Item>{String(x.sku_name??x.batch_code??'')} · {display(x.affected_quantity??x.net_amount)}</List.Item>}/></Card>
}
export function BatchDetail({id}:{id:number}){
 const {membership}=useAuth();const qc=can(membership,'QUALITY_INSPECTOR');const supplier=membership?.organizationType==='SUPPLIER';const [scan,setScan]=useState('');const navigate=useNavigate()
 const q=useQuery({queryKey:['batch',id],queryFn:()=>api<Row>(`/batches/${id}`)});const docs=useRows(`/batches/${id}/document-requests`);const b=q.data
 const refresh=()=>{void q.refetch();void docs.refetch()}
 return <><Space><Input placeholder="Mã QR / mã lô để tìm" value={scan} onChange={e=>setScan(e.target.value)}/><Button onClick={()=>navigate('/portal/batches?search='+encodeURIComponent(scan))}>Tìm lô</Button></Space><Card loading={q.isPending} title={String(b?.batch_code??'Chi tiết lô')}>{q.error&&<Alert type="error" message={q.error.message}/>}<Descriptions items={['sku_name','supplier_name','declared_quantity','accepted_quantity','review_quantity','rejected_quantity','batch_status','trace_note'].map(k=>({key:k,label:({sku_name:'Sản phẩm',supplier_name:'NCC',declared_quantity:'Khai báo',accepted_quantity:'Đạt',review_quantity:'Giữ lại',rejected_quantity:'Từ chối',batch_status:'Trạng thái',trace_note:'Nguồn gốc'} as Record<string,string>)[k],children:display(b?.[k],k)}))}/><QrButton type="BATCH" id={id}/></Card>
 {supplier&&b?.batch_status==='CREATED'&&<><ActionForm title="Sửa lô" method="PUT" path={`/batches/${id}`} fields={[{name:'quantity',label:'Số lượng',type:'number',min:0.001,initial:b.declared_quantity},{name:'origin',label:'Nguồn gốc',type:'textarea',initial:b.trace_note}]} onDone={refresh}/><ActionForm title="Hủy lô chưa kiểm" path={`/batches/${id}/cancel`} fields={[{name:'reason',label:'Lý do'}]} onDone={refresh}/></>}
 {qc&&b?.batch_status==='CREATED'&&<ActionForm title="Kiểm nhận lô" path={`/batches/${id}/inspect`} fields={[{name:'accepted',label:'Đạt',type:'number',initial:b.declared_quantity},{name:'review',label:'Giữ lại',type:'number',initial:0},{name:'rejected',label:'Từ chối (gồm lượng thiếu)',type:'number',initial:0},{name:'note',label:'Kết quả kiểm nhận',type:'textarea'},{name:'evidenceId',label:'Ảnh kiểm nhận',type:'file',required:false},...['SPECIFICATION','PACKAGING','LABEL','APPEARANCE'].map((name,i)=>({name,label:['Quy cách','Bao bì','Nhãn','Ngoại quan'][i],type:'select' as const,initial:'PASS',options:[{value:'PASS',label:'Đạt'},{value:'REVIEW',label:'Cần kiểm lại'},{value:'FAIL',label:'Không đạt'}]}))]} transform={v=>{if(Math.abs(Number(v.accepted)+Number(v.review)+Number(v.rejected)-Number(b.declared_quantity))>0.00001)throw new Error('Tổng đạt + giữ + từ chối phải bằng lượng khai báo');return {...v,checklist:Object.fromEntries(['SPECIFICATION','PACKAGING','LABEL','APPEARANCE'].map(k=>[k,v[k]]))}}} onDone={refresh}/>}
 {qc&&Number(b?.review_quantity)>0&&<ActionForm title="Tái kiểm lượng cách ly" path={`/batches/${id}/reinspect`} fields={[{name:'accepted',label:'Đạt sau tái kiểm',type:'number',initial:b?.review_quantity},{name:'rejected',label:'Từ chối',type:'number',initial:0},{name:'note',label:'Kết luận',type:'textarea'}]} transform={v=>{if(Math.abs(Number(v.accepted)+Number(v.rejected)-Number(b?.review_quantity))>0.00001)throw new Error('Tổng phải bằng lượng cách ly');return v}} onDone={refresh}/>}
 {qc&&<ActionForm title="Yêu cầu bổ sung hồ sơ" path={`/batches/${id}/document-requests`} fields={[{name:'documentType',label:'Loại hồ sơ'},{name:'message',label:'Nội dung cần bổ sung',type:'textarea'}]} onDone={refresh}/>}
 <Card title="Hồ sơ bổ sung">{docs.error&&<Alert type="error" message={docs.error.message}/>}<List dataSource={docs.data??[]} renderItem={d=><List.Item><Space direction="vertical"><strong>{String(d.document_type)} · {display(d.status)}</strong><p>{String(d.message)}</p>{d.submitted_file_id!=null&&<EvidenceLink id={Number(d.submitted_file_id)}/>} {supplier&&['OPEN','REJECTED'].includes(String(d.status))&&<ActionForm title="Nộp hồ sơ" path={`/batches/document-requests/${d.document_request_id}/submit`} fields={[{name:'fileId',label:'Tệp',type:'file'},{name:'note',label:'Ghi chú',required:false}]} onDone={refresh}/>} {qc&&d.status==='SUBMITTED'&&<ActionForm title="Duyệt hồ sơ" path={`/batches/document-requests/${d.document_request_id}/review`} fields={[{name:'accepted',label:'Kết quả',type:'select',options:[{value:'yes',label:'Chấp nhận'},{value:'no',label:'Bổ sung lại'}]},{name:'note',label:'Phản hồi'}]} transform={v=>({...v,accepted:v.accepted==='yes'})} onDone={refresh}/>}</Space></List.Item>}/></Card>
 <Card title="Lịch sử kiểm nhận"><Timeline items={(b?.inspections as Row[]??[]).map(x=>({children:<>{display(x.inspected_at,'inspected_at')} · {String(x.general_note)} · Đạt {String(x.accepted_quantity)}, giữ {String(x.review_quantity)}, từ chối {String(x.rejected_quantity)}</>}))}/></Card></>
}

export function AdminPage(){
 const [tab,setTab]=useUrlTab('partners');const [selected,setSelected]=useState<Row>();const [error,setError]=useState('');const [preview,setPreview]=useState<string>();const partners=useRows('/admin/partners')
 return <>{error&&<Alert type="error" message={error}/>}<Tabs activeKey={tab} onChange={setTab} items={[
 {key:'partners',label:'Đối tác',children:<><DataTable path="/admin/partners" rowKey="organization_id" columns={[[ 'organization_name','Đơn vị'],['organization_type','Loại'],['status','Trạng thái']]} actions={r=><Space><Button onClick={()=>setSelected(r)}>Xem / xử lý</Button>{r.status==='PENDING'&&<Button onClick={async()=>{try{await api(`/admin/partners/${r.organization_id}/approve`,'POST');await partners.refetch()}catch(e){setError((e as Error).message)}}}>Duyệt</Button>}</Space>}/>{selected&&<><ActionForm key={String(selected.organization_id)} title={`Xử lý ${selected.organization_name}`} method="PATCH" path={`/admin/partners/${selected.organization_id}/status`} fields={[{name:'status',label:'Trạng thái',type:'select',options:[{value:'REJECTED',label:'Từ chối'},{value:'SUSPENDED',label:'Tạm dừng'},{value:'ACTIVE',label:'Kích hoạt lại'}]},{name:'reason',label:'Lý do',type:'textarea'}]}/><ActionForm title="Yêu cầu bổ sung đăng ký" path={`/admin/partners/${selected.organization_id}/request-information`} fields={[{name:'reason',label:'Nội dung cần bổ sung',type:'textarea'}]}/></>}</>},
 {key:'staff',label:'Nhân viên & quyền',children:<><DataTable path="/admin/staff" rowKey="user_id" columns={[[ 'full_name','Họ tên'],['email','Email'],['roles','Quyền'],['status','Trạng thái']]} actions={r=><Button onClick={()=>setSelected(r)}>Sửa</Button>}/>{selected?.user_id!=null&&<ActionForm key={String(selected.user_id)} title="Cập nhật nhân viên" method="PUT" path={`/admin/staff/${selected.user_id}`} fields={[{name:'fullName',label:'Họ tên',initial:selected.full_name},{name:'status',label:'Trạng thái',type:'select',initial:selected.status,options:[{value:'ACTIVE',label:'Hoạt động'},{value:'DISABLED',label:'Khóa'}]},{name:'roles',label:'Quyền',type:'multiple',initial:selected.roles,options:Object.entries(roleNames).filter(([r])=>['OPERATIONS_COORDINATOR','QUALITY_INSPECTOR','ACCOUNTANT','CUSTOMER_SUPPORT','DRIVER'].includes(r)).map(([value,label])=>({value,label}))}]}/>}<OperationsPage initialTab="partners"/></>},
 {key:'catalog',label:'Danh mục & giá',children:<OperationsPage initialTab="prices"/>},
 {key:'audit',label:'Nhật ký',children:<DataTable path="/admin/audit-logs" rowKey="audit_log_id" columns={[[ 'actor_email','Người thực hiện'],['action_code','Hành động'],['entity_type','Đối tượng'],['entity_id','Mã nội bộ'],['occurred_at','Thời gian']]}/>},
 {key:'logins',label:'Đăng nhập',children:<DataTable path="/admin/login-history" rowKey="login_history_id" columns={[[ 'email','Email'],['success','Thành công'],['ip_address','Địa chỉ IP'],['occurred_at','Thời gian']]}/>},
 {key:'system',label:'Hệ thống',children:<SystemCheckPage/>},
 {key:'preview',label:'Xem trước vai trò',children:<Card><Space wrap>{Object.entries(roleNames).filter(([r])=>r!=='SYSTEM_ADMIN').map(([r,n])=><Button key={r} onClick={async()=>{try{await api('/admin/preview','POST',{role:r});setPreview(r)}catch(e){setError((e as Error).message)}}}>{n}</Button>)}</Space>{preview&&<Alert type="info" message={`Xem trước: ${roleNames[preview]}`} description="Đây là chế độ mô tả quyền, không có thao tác ghi và không giả danh tài khoản khác."/>}</Card>},
 ]}/></>
}
