package vn.freshlink.identity;
import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import vn.freshlink.common.*;import vn.freshlink.common.api.ApiResponse;
@RestController public class OrganizationMemberController{
 private final JdbcTemplate jdbc;private final Sql sql;private final PasswordEncoder passwords;public OrganizationMemberController(JdbcTemplate j,Sql s,PasswordEncoder p){jdbc=j;sql=s;passwords=p;}
 public record Invite(@NotBlank @Email @Size(max=150) String email,@NotBlank @Size(max=40) String roleCode){}
 public record Accept(@NotBlank @Size(max=150) String token,@NotBlank @Size(max=150) String fullName,@Size(max=20) String phone,@NotBlank @Size(min=12,max=72) String password){}
 public record RoleUpdate(@NotEmpty @Size(max=10) Set<@NotBlank String> roles){}
 private String hash(String v){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private void manage(Actor a,long org){a.requireOrganization(org,"RESTAURANT_MANAGER","SUPPLIER_MANAGER");}
 @GetMapping("/api/organizations/{org}/members") public ApiResponse<?> list(@AuthenticationPrincipal Actor a,@PathVariable long org){manage(a,org);return ApiResponse.success(jdbc.queryForList("SELECT m.member_id,m.user_id,u.email,u.full_name,u.phone,m.job_title,m.status,m.joined_at,GROUP_CONCAT(r.role_code ORDER BY r.role_code) roles FROM organization_members m JOIN users u ON u.user_id=m.user_id LEFT JOIN member_roles mr ON mr.member_id=m.member_id LEFT JOIN roles r ON r.role_id=mr.role_id WHERE m.organization_id=? GROUP BY m.member_id,m.user_id,u.email,u.full_name,u.phone,m.job_title,m.status,m.joined_at ORDER BY m.member_id",org),"Thành viên");}
 @PostMapping("/api/organizations/{org}/invitations") @Transactional public ApiResponse<?> invite(@AuthenticationPrincipal Actor a,@PathVariable long org,@jakarta.validation.Valid @RequestBody Invite r){manage(a,org);String type=jdbc.queryForObject("SELECT organization_type FROM organizations WHERE organization_id=?",String.class,org),prefix="RESTAURANT".equals(type)?"RESTAURANT_":"SUPPLIER".equals(type)?"SUPPLIER_":"";if(prefix.isEmpty()||!r.roleCode().startsWith(prefix)||jdbc.queryForObject("SELECT COUNT(*) FROM roles WHERE role_code=?",Integer.class,r.roleCode())!=1)throw new IllegalArgumentException("Vai trò không hợp lệ cho tổ chức");jdbc.update("UPDATE organization_invitations SET status='REVOKED' WHERE organization_id=? AND email=? AND status='PENDING'",org,r.email().toLowerCase());String token=UUID.randomUUID()+"."+UUID.randomUUID();long id=sql.insert("INSERT INTO organization_invitations(organization_id,email,role_code,token_hash,invited_by,expires_at) VALUES (?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 7 DAY))",org,r.email().toLowerCase(),r.roleCode(),hash(token),a.userId());return ApiResponse.success(Map.of("invitationId",id,"token",token,"expiresAt",Instant.now().plus(Duration.ofDays(7))),"Đã tạo lời mời; gửi token này qua kênh bảo mật");}
 @PostMapping("/api/public/invitations/accept") @Transactional public ApiResponse<?> accept(@jakarta.validation.Valid @RequestBody Accept r){var xs=jdbc.queryForList("SELECT * FROM organization_invitations WHERE token_hash=? FOR UPDATE",hash(r.token()));if(xs.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Lời mời không tồn tại");var x=xs.get(0);if(!"PENDING".equals(x.get("status"))||((java.sql.Timestamp)x.get("expires_at")).toInstant().isBefore(Instant.now()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Lời mời đã hết hiệu lực");var users=jdbc.queryForList("SELECT user_id FROM users WHERE email=? FOR UPDATE",Long.class,x.get("email"));long user;if(users.isEmpty())user=sql.insert("INSERT INTO users(email,password_hash,full_name,phone,status) VALUES (?,?,?,?,'ACTIVE')",x.get("email"),passwords.encode(r.password()),r.fullName(),r.phone());else user=users.get(0);long member;var ms=jdbc.queryForList("SELECT member_id FROM organization_members WHERE organization_id=? AND user_id=?",Long.class,x.get("organization_id"),user);if(ms.isEmpty())member=sql.insert("INSERT INTO organization_members(organization_id,user_id,status,joined_at) VALUES (?,?,'ACTIVE',UTC_TIMESTAMP(3))",x.get("organization_id"),user);else{member=ms.get(0);jdbc.update("UPDATE organization_members SET status='ACTIVE',joined_at=UTC_TIMESTAMP(3) WHERE member_id=?",member);}jdbc.update("INSERT IGNORE INTO member_roles(member_id,role_id) SELECT ?,role_id FROM roles WHERE role_code=?",member,x.get("role_code"));jdbc.update("UPDATE organization_invitations SET status='ACCEPTED',accepted_at=UTC_TIMESTAMP(3) WHERE invitation_id=?",x.get("invitation_id"));return ApiResponse.success(member,"Đã tham gia tổ chức");}
 @PutMapping("/api/organizations/{org}/members/{member}/roles") @Transactional public ApiResponse<?> roles(@AuthenticationPrincipal Actor a,@PathVariable long org,@PathVariable long member,@jakarta.validation.Valid @RequestBody RoleUpdate r){manage(a,org);if(jdbc.queryForObject("SELECT COUNT(*) FROM organization_members WHERE member_id=? AND organization_id=?",Integer.class,member,org)!=1)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy thành viên");String type=jdbc.queryForObject("SELECT organization_type FROM organizations WHERE organization_id=?",String.class,org),prefix="RESTAURANT".equals(type)?"RESTAURANT_":"SUPPLIER_";for(String role:r.roles())if(!role.startsWith(prefix)||jdbc.queryForObject("SELECT COUNT(*) FROM roles WHERE role_code=?",Integer.class,role)!=1)throw new IllegalArgumentException("Vai trò không hợp lệ");jdbc.update("DELETE FROM member_roles WHERE member_id=?",member);for(String role:r.roles())jdbc.update("INSERT INTO member_roles(member_id,role_id,assigned_by) SELECT ?,role_id,? FROM roles WHERE role_code=?",member,a.userId(),role);return ApiResponse.success(member,"Đã cập nhật vai trò");}
 @DeleteMapping("/api/organizations/{org}/members/{member}") @Transactional public ApiResponse<?> disable(@AuthenticationPrincipal Actor a,@PathVariable long org,@PathVariable long member){manage(a,org);if(jdbc.update("UPDATE organization_members SET status='DISABLED' WHERE member_id=? AND organization_id=? AND user_id<>?",member,org,a.userId())!=1)throw new ResponseStatusException(HttpStatus.CONFLICT,"Không thể vô hiệu hóa thành viên");return ApiResponse.success(member,"Đã vô hiệu hóa thành viên");}
}
